name: Deploy Infrastructure

on:
  workflow_dispatch:
    inputs:
      ENV:
        default: dev

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn

      - name: serverless deploy - development
        uses: serverless/github-action@v3.2
        if: ${{ github.event.inputs.ENV == 'dev' }}
        with:
          args: deploy --verbose --region us-west-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_DEV_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_DEV_ACCESS_KEY }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_DEV_API_KEY }}
          KNACK_API_KEY: ${{ secrets.KNACK_DEV_API_KEY }}
          KNACK_APP_ID: ${{ secrets.KNACK_DEV_APP_ID }}

      - name: serverless deploy - production
        uses: serverless/github-action@v3.2
        if: ${{ github.event.inputs.ENV == 'prod' }}
        with:
          args: deploy --stage prod --verbose
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_PROD_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_PROD_ACCESS_KEY }}
          MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_PROD_API_KEY }}
          KNACK_API_KEY: ${{ secrets.KNACK_PROD_API_KEY }}
          KNACK_APP_ID: ${{ secrets.KNACK_PROD_APP_ID }}
